largest-companies:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: root
      password: root
      port: 5432
      dbname: postgres # or database instead of dbname
      schema: public
      threads: 1
      